In [73]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout
from tensorflow.keras.callbacks import EarlyStopping
from sklearn.model_selection import train_test_split
from sklearn.metrics import r2_score, mean_absolute_error, mean_squared_error
from sklearn.preprocessing import StandardScaler

In [3]:
df=pd.read_csv('/kaggle/input/datasets/brendan45774/test-file/tested.csv')

In [6]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,0,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

In [7]:
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,418.000000,418.000000,418.000000,332.000000,418.000000,418.000000,417.000000
mean,1100.500000,0.363636,2.265550,30.272590,0.447368,0.392344,35.627188
std,120.810458,0.481622,0.841838,14.181209,0.896760,0.981429,55.907576
min,892.000000,0.000000,1.000000,0.170000,0.000000,0.000000,0.000000
25%,996.250000,0.000000,1.000000,21.000000,0.000000,0.000000,7.895800
50%,1100.500000,0.000000,3.000000,27.000000,0.000000,0.000000,14.454200
75%,1204.750000,1.000000,3.000000,39.000000,1.000000,0.000000,31.500000
max,1309.000000,1.000000,3.000000,76.000000,8.000000,9.000000,512.329200

In [10]:
df.isnull().sum()/len(df)*100

PassengerId     0.000000
Survived        0.000000
Pclass          0.000000
Name            0.000000
Sex             0.000000
Age            20.574163
SibSp           0.000000
Parch           0.000000
Ticket          0.000000
Fare            0.239234
Cabin          78.229665
Embarked        0.000000
dtype: float64

In [34]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 418 entries, 0 to 417
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  418 non-null    int64
 1   Survived     418 non-null    int64
 2   Pclass       418 non-null    int64
 3   Name         418 non-null    object
 4   Sex          418 non-null    object
 5   Age          332 non-null    float64
 6   SibSp        418 non-null    int64
 7   Parch        418 non-null    int64
 8   Ticket       418 non-null    object
 9   Fare         417 non-null    float64
 10  Cabin        91 non-null     object
 11  Embarked     418 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 39.3+ KB

In [15]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,0,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S

In [19]:
#workable data 
data=df.drop(['PassengerId','Name','Cabin'],axis=1)

In [33]:
data['Age'].mode()

0    21.0
1    24.0
Name: Age, dtype: float64

In [37]:
data['Age']=data['Age'].fillna(data['Age'].median())

In [57]:
data=data.dropna()

In [58]:
data.isnull().sum()

Survived    0
Pclass      0
Sex         0
Age         0
SibSp       0
Parch       0
Ticket      0
Fare        0
Embarked    0
dtype: int64

In [59]:
data.head()

   Survived  Pclass  Sex   Age  SibSp  Parch   Ticket     Fare Embarked
0         0       3    0  34.5      0      0   330911   7.8292        Q
1         1       3    1  47.0      1      0   363272   7.0000        S
2         0       2    0  62.0      0      0   240276   9.6875        Q
3         0       3    0  27.0      0      0   315154   8.6625        S
4         1       3    1  22.0      1      1  3101298  12.2875        S

In [61]:
data.select_dtypes('object').info()

<class 'pandas.core.frame.DataFrame'>
Index: 417 entries, 0 to 417
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Ticket    417 non-null    object
 1   Embarked  417 non-null    object
dtypes: object(2)
memory usage: 9.8+ KB

In [50]:
data['Sex']=data['Sex'].map({'male':0,'female':1})

In [63]:
data=data.drop('Ticket',axis=1)

In [65]:
data=pd.get_dummies(data)

In [66]:
data.head()

,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked_C,Embarked_Q,Embarked_S
0,0,3,0,34.5,0,0,7.8292,False,True,False
1,1,3,1,47.0,1,0,7.0000,False,False,True
2,0,2,0,62.0,0,0,9.6875,False,True,False
3,0,3,0,27.0,0,0,8.6625,False,False,True
4,1,3,1,22.0,1,1,12.2875,False,False,True

In [88]:
x=data.drop('Fare',axis=1)

In [89]:
y=data['Fare']

In [90]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.1,random_state=42)

In [91]:
ss=StandardScaler()

In [92]:
x_train=ss.fit_transform(x_train)

In [93]:
x_test=ss.transform(x_test)

In [118]:
#model
model=Sequential([
    Dense(64,activation='relu',input_shape=(x_train.shape[1],)),
    Dropout(0.3),

    Dense(32,activation='relu'),
    Dropout(0.2),

    Dense(16,activation='relu'),
    Dropout(0.2),

    Dense(1,activation='linear')
])

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [119]:
model.summary()

Model: "sequential_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_12 (Dense)                │ (None, 64)             │           640 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_8 (Dropout)             │ (None, 64)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_13 (Dense)                │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_9 (Dropout)             │ (None, 32)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_14 (Dense)                │ (None, 16)             │           528 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_10 (Dropout)            │ (None, 16)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_15 (Dense)                │ (None, 1)              │            17 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 3,265 (12.75 KB)

 Trainable params: 3,265 (12.75 KB)

 Non-trainable params: 0 (0.00 B)

In [120]:
model.compile(optimizer='adam',loss='mse',metrics=['mae'])

In [121]:
early_stop=EarlyStopping(
    monitor='val_loss',
    patience=100,
    restore_best_weights=True
)

In [122]:
history=model.fit(x_train,y_train,epochs=300,batch_size=1,validation_split=0.1,callbacks=[early_stop])

Epoch 1/300
337/337 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 2728.5718 - mae: 26.4757 - val_loss: 313.0354 - val_mae: 12.5736
Epoch 2/300
337/337 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 2207.0027 - mae: 28.2796 - val_loss: 581.3041 - val_mae: 14.3240
Epoch 3/300
337/337 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 2750.2854 - mae: 27.2108 - val_loss: 469.2794 - val_mae: 12.5473
Epoch 4/300
337/337 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 2120.8115 - mae: 23.8664 - val_loss: 353.2761 - val_mae: 11.0102
Epoch 5/300
337/337 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 1849.7747 - mae: 21.8401 - val_loss: 410.3017 - val_mae: 11.6448
Epoch 6/300
337/337 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 1855.5859 - mae: 22.5310 - val_loss: 496.8861 - val_mae: 12.3855
Epoch 7/300
337/337 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 2048.3044 - mae: 24.4985 - val_loss: 419.8221 - val_mae: 11.9684
Epoch 8/300
337/337 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 1454.1694 - mae: 19.9737 - val_loss: 1067.6216 - val_mae: 16.7684
Epoch 9/300
337/337 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 1763.1216 - mae: 23.4344 - val_loss: 404.4148 - val_mae: 11.6427
Epoch 10/300
337/337 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 1647.7605 - mae: 20.4426 - val_loss: 405.2148 - val_mae: 12.2201
Epoch 11/300
337/337 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 1512.5085 - mae: 19.4937 - val_loss: 374.1392 - val_mae: 11.3144
Epoch 12/300
337/337 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 2720.4702 - mae: 26.5953 - val_loss: 322.7222 - val_mae: 11.2846
Epoch 13/300
337/337 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 2041.2754 - mae: 19.4491 - val_loss: 561.9741 - val_mae: 13.0382
Epoch 14/300
337/337 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 1397.5242 - mae: 18.7939 - val_loss: 737.7420 - val_mae: 13.7123
Epoch 15/300
337/337 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 1986.4512 - mae: 22.8093 - val_loss: 920.6453 - val_mae: 15.1313
Epoch 16/300
337/337 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 2056.5571 - mae: 21.6395 - val_loss: 418.9736 - val_mae: 12.0825
Epoch 17/300
337/337 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 1474.5365 - mae: 18.1974 - val_loss: 326.7511 - val_mae: 11.0189
Epoch 18/300
337/337 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 1767.9220 - mae: 20.6184 - val_loss: 641.7405 - val_mae: 13.4142
Epoch 19/300
337/337 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 2675.9341 - mae: 27.3621 - val_loss: 246.2503 - val_mae: 10.7096
Epoch 20/300
337/337 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 1385.5752 - mae: 18.3912 - val_loss: 701.0284 - val_mae: 13.8411
Epoch 21/300
337/337 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 1510.3236 - mae: 19.7349 - val_loss: 536.9955 - val_mae: 12.7866
Epoch 22/300
337/337 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 1441.6532 - mae: 18.7739 - val_loss: 545.2721 - val_mae: 12.7683
Epoch 23/300
337/337 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 1796.9060 - mae: 20.6113 - val_loss: 426.0694 - val_mae: 11.5415
Epoch 24/300
337/337 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 1910.6648 - mae: 20.4022 - val_loss: 356.5502 - val_mae: 11.3377
Epoch 25/300
337/337 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 1345.1616 - mae: 16.3947 - val_loss: 494.4573 - val_mae: 12.6041
Epoch 26/300
337/337 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 1300.7814 - mae: 17.8169 - val_loss: 256.5358 - val_mae: 10.4823
Epoch 27/300
337/337 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 1674.6984 - mae: 18.5516 - val_loss: 309.6944 - val_mae: 10.7600
Epoch 28/300
337/337 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 1982.3752 - mae: 20.4843 - val_loss: 338.9038 - val_mae: 10.8935
Epoch 29/300
337/337 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 1278.5306 - mae: 18.0008 - val_loss: 640.3013 - val_mae: 12.8465
Epoch 30/300
337/337 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 2482.7188 - mae: 24.3835 - val_loss: 416.1702 - val_mae: 11.4462
Epoch 31/300
337/337 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 2302.3257 - mae: 19.3151 - val_loss: 259.2099 - val_mae: 9.9556
Epoch 32/300
337/337 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 2701.2683 - mae: 21.5450 - val_loss: 269.5955 - val_mae: 9.7988
Epoch 33/300
337/337 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 1178.5602 - mae: 15.6927 - val_loss: 511.7031 - val_mae: 11.9674
Epoch 34/300
337/337 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 1708.8608 - mae: 19.0933 - val_loss: 291.0312 - val_mae: 10.2793
Epoch 35/300
337/337 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 1483.4955 - mae: 18.2207 - val_loss: 528.3607 - val_mae: 12.3990
Epoch 36/300
337/337 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 1512.5680 - mae: 19.0902 - val_loss: 494.3011 - val_mae: 12.1886
Epoch 37/300
337/337 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 2055.4985 - mae: 19.4627 - val_loss: 276.1283 - val_mae: 10.0629
Epoch 38/300
337/337 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 1605.6869 - mae: 19.2892 - val_loss: 722.6219 - val_mae: 13.3036
Epoch 39/300
337/337 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 1428.9753 - mae: 17.7119 - val_loss: 604.9786 - val_mae: 12.4823
Epoch 40/300
337/337 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 1607.0585 - mae: 20.2822 - val_loss: 785.6238 - val_mae: 14.0893
Epoch 41/300
337/337 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 3177.8826 - mae: 21.6805 - val_loss: 698.3309 - val_mae: 13.3763
Epoch 42/300
337/337 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 1988.5374 - mae: 21.6204 - val_loss: 570.0381 - val_mae: 12.5654
Epoch 43/300
337/337 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 877.0042 - mae: 13.4730 - val_loss: 776.8412 - val_mae: 13.8364
Epoch 44/300
337/337 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 1465.8882 - mae: 18.6130 - val_loss: 379.4257 - val_mae: 10.8036
Epoch 45/300
337/337 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 1204.6963 - mae: 17.1061 - val_loss: 588.4753 - val_mae: 12.2650
Epoch 46/300
337/337 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 1213.0299 - mae: 17.5149 - val_loss: 599.1639 - val_mae: 12.5155
Epoch 47/300
337/337 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 1548.9868 - mae: 17.7364 - val_loss: 309.3786 - val_mae: 10.0913
Epoch 48/300
337/337 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 1623.1050 - mae: 17.0027 - val_loss: 434.8638 - val_mae: 11.3650
Epoch 49/300
337/337 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 1374.8248 - mae: 17.8580 - val_loss: 462.0009 - val_mae: 11.4495
Epoch 50/300
337/337 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 1882.3953 - mae: 20.4486 - val_loss: 317.7315 - val_mae: 10.2117
Epoch 51/300
337/337 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 1826.8593 - mae: 19.0329 - val_loss: 491.6396 - val_mae: 11.5316
Epoch 52/300
337/337 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 2139.6802 - mae: 20.0870 - val_loss: 314.5821 - val_mae: 10.1065
Epoch 53/300
337/337 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 1380.1177 - mae: 19.0295 - val_loss: 404.3973 - val_mae: 10.6339
Epoch 54/300
337/337 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 1524.0476 - mae: 17.9790 - val_loss: 306.3520 - val_mae: 9.8550
Epoch 55/300
337/337 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 1192.8346 - mae: 16.2332 - val_loss: 338.8279 - val_mae: 9.7621
Epoch 56/300
337/337 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 1727.0654 - mae: 19.2256 - val_loss: 251.5374 - val_mae: 9.2031
Epoch 57/300
337/337 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 1529.0291 - mae: 18.5297 - val_loss: 175.4386 - val_mae: 7.9767
Epoch 58/300
337/337 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 1480.7047 - mae: 16.7337 - val_loss: 331.7472 - val_mae: 9.7476
Epoch 59/300
337/337 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 1848.8662 - mae: 18.1900 - val_loss: 268.5434 - val_mae: 8.8295
Epoch 60/300
337/337 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 1232.6862 - mae: 18.6172 - val_loss: 420.5948 - val_mae: 10.4589
Epoch 61/300
337/337 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 1312.9465 - mae: 17.2787 - val_loss: 401.8283 - val_mae: 9.9462
Epoch 62/300
337/337 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 1455.9867 - mae: 19.1653 - val_loss: 800.4194 - val_mae: 13.7475
Epoch 63/300
337/337 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 2320.9216 - mae: 22.0343 - val_loss: 265.6649 - val_mae: 9.1578
Epoch 64/300
337/337 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 1243.4138 - mae: 16.5795 - val_loss: 551.1313 - val_mae: 11.4793
Epoch 65/300
337/337 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 909.6307 - mae: 14.6207 - val_loss: 443.2935 - val_mae: 10.5230
Epoch 66/300
337/337 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 1032.8131 - mae: 14.9017 - val_loss: 566.8538 - val_mae: 11.4384
Epoch 67/300
337/337 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 3283.3882 - mae: 23.5344 - val_loss: 271.1063 - val_mae: 9.1586
Epoch 68/300
337/337 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 1665.0234 - mae: 18.3858 - val_loss: 275.0027 - val_mae: 9.5796
Epoch 69/300
337/337 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 1184.5308 - mae: 16.9081 - val_loss: 669.5193 - val_mae: 12.4840
Epoch 70/300
337/337 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 1645.1028 - mae: 18.1423 - val_loss: 735.1538 - val_mae: 13.2133
Epoch 71/300
337/337 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 1571.1403 - mae: 19.2902 - val_loss: 409.5509 - val_mae: 9.6817
Epoch 72/300
337/337 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 1597.2039 - mae: 18.4978 - val_loss: 366.7308 - val_mae: 9.6109
Epoch 73/300
337/337 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 936.4984 - mae: 16.0958 - val_loss: 901.2488 - val_mae: 14.5596
Epoch 74/300
337/337 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 1731.4564 - mae: 20.0841 - val_loss: 249.8442 - val_mae: 8.7005
Epoch 75/300
337/337 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 1375.1136 - mae: 15.9483 - val_loss: 494.2871 - val_mae: 11.3641
Epoch 76/300
337/337 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 1994.2513 - mae: 19.7196 - val_loss: 297.8976 - val_mae: 9.2188
Epoch 77/300
337/337 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 1368.0530 - mae: 16.7858 - val_loss: 415.5766 - val_mae: 10.2202
Epoch 78/300
337/337 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 1941.3518 - mae: 20.3170 - val_loss: 266.2611 - val_mae: 8.9903
Epoch 79/300
337/337 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 1117.8217 - mae: 14.7165 - val_loss: 705.5276 - val_mae: 12.5788
Epoch 80/300
337/337 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 1381.7867 - mae: 16.9881 - val_loss: 374.7151 - val_mae: 9.9637
Epoch 81/300
337/337 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 855.9497 - mae: 13.7188 - val_loss: 247.1039 - val_mae: 8.6083
Epoch 82/300
337/337 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 1361.7653 - mae: 18.1654 - val_loss: 683.8945 - val_mae: 12.4989
Epoch 83/300
337/337 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 1660.6737 - mae: 18.4061 - val_loss: 421.0599 - val_mae: 9.9934
Epoch 84/300
337/337 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 1069.5450 - mae: 15.2258 - val_loss: 447.5898 - val_mae: 10.2996
Epoch 85/300
337/337 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 1046.1652 - mae: 16.6741 - val_loss: 964.4395 - val_mae: 14.7151
Epoch 86/300
337/337 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 1629.1805 - mae: 19.8415 - val_loss: 325.9498 - val_mae: 9.2455
Epoch 87/300
337/337 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 1124.4495 - mae: 15.6895 - val_loss: 651.7784 - val_mae: 12.3717
Epoch 88/300
337/337 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 2058.4307 - mae: 17.8741 - val_loss: 386.4156 - val_mae: 9.9352
Epoch 89/300
337/337 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 1454.3124 - mae: 18.1685 - val_loss: 852.9245 - val_mae: 14.2172
Epoch 90/300
337/337 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 1168.2826 - mae: 16.2049 - val_loss: 308.8259 - val_mae: 9.1084
Epoch 91/300
337/337 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 1171.4647 - mae: 15.1214 - val_loss: 490.4077 - val_mae: 10.7734
Epoch 92/300
337/337 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 2236.4080 - mae: 20.6698 - val_loss: 588.5506 - val_mae: 11.5907
Epoch 93/300
337/337 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 1036.6688 - mae: 15.0350 - val_loss: 335.7887 - val_mae: 9.1883
Epoch 94/300
337/337 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 1546.8940 - mae: 17.8761 - val_loss: 300.3759 - val_mae: 8.9118
Epoch 95/300
337/337 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 1922.9883 - mae: 20.4605 - val_loss: 586.3721 - val_mae: 11.6749
Epoch 96/300
337/337 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 1057.9475 - mae: 14.7236 - val_loss: 521.7343 - val_mae: 11.0419
Epoch 97/300
337/337 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 1692.7296 - mae: 20.4753 - val_loss: 438.8205 - val_mae: 9.7986
Epoch 98/300
337/337 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 1960.0750 - mae: 19.1677 - val_loss: 270.7779 - val_mae: 8.4025
Epoch 99/300
337/337 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 2760.3682 - mae: 20.9546 - val_loss: 585.8423 - val_mae: 11.2049
Epoch 100/300
337/337 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 1533.5198 - mae: 16.5893 - val_loss: 733.7054 - val_mae: 12.3072
Epoch 101/300
337/337 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 1283.1750 - mae: 16.4887 - val_loss: 523.4897 - val_mae: 11.0811
Epoch 102/300
337/337 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 1700.7302 - mae: 17.4551 - val_loss: 445.7715 - val_mae: 10.1941
Epoch 103/300
337/337 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 1469.6954 - mae: 16.0672 - val_loss: 573.2825 - val_mae: 11.6519
Epoch 104/300
337/337 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 1438.0339 - mae: 16.3610 - val_loss: 322.6523 - val_mae: 9.3105
Epoch 105/300
337/337 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 1561.6334 - mae: 18.3456 - val_loss: 320.7827 - val_mae: 9.2201
Epoch 106/300
337/337 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 1657.4813 - mae: 18.1163 - val_loss: 563.3997 - val_mae: 11.5007
Epoch 107/300
337/337 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 1523.1780 - mae: 18.2244 - val_loss: 350.8734 - val_mae: 9.6229
Epoch 108/300
337/337 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 2179.3474 - mae: 18.2140 - val_loss: 430.5132 - val_mae: 10.3035
Epoch 109/300
337/337 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 1690.7816 - mae: 19.2789 - val_loss: 677.2552 - val_mae: 12.4897
Epoch 110/300
337/337 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 1343.3885 - mae: 18.3078 - val_loss: 1121.3430 - val_mae: 15.5391
Epoch 111/300
337/337 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 1283.1627 - mae: 16.2954 - val_loss: 446.2211 - val_mae: 10.2304
Epoch 112/300
337/337 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 1597.6562 - mae: 18.1507 - val_loss: 234.7639 - val_mae: 8.6979
Epoch 113/300
337/337 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 1818.2761 - mae: 18.5579 - val_loss: 460.4066 - val_mae: 10.2324
Epoch 114/300
337/337 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 1193.3945 - mae: 16.5734 - val_loss: 565.0851 - val_mae: 11.1315
Epoch 115/300
337/337 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 1410.4536 - mae: 17.1544 - val_loss: 239.5275 - val_mae: 8.2948
Epoch 116/300
337/337 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 1448.1141 - mae: 15.8647 - val_loss: 412.1423 - val_mae: 9.6185
Epoch 117/300
337/337 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 2077.5925 - mae: 19.8731 - val_loss: 233.0326 - val_mae: 8.3429
Epoch 118/300
337/337 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 1832.4926 - mae: 18.2035 - val_loss: 392.7354 - val_mae: 9.5433
Epoch 119/300
337/337 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 1042.8887 - mae: 13.8457 - val_loss: 349.8669 - val_mae: 9.3138
Epoch 120/300
337/337 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 2366.8013 - mae: 17.2613 - val_loss: 678.7961 - val_mae: 12.2947
Epoch 121/300
337/337 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 1140.4990 - mae: 16.2983 - val_loss: 518.8048 - val_mae: 10.6834
Epoch 122/300
337/337 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 2006.1486 - mae: 21.2092 - val_loss: 327.5727 - val_mae: 8.7124
Epoch 123/300
337/337 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 1276.7485 - mae: 17.8080 - val_loss: 660.7552 - val_mae: 12.3357
Epoch 124/300
337/337 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 1055.4271 - mae: 14.8017 - val_loss: 762.3572 - val_mae: 12.8764
Epoch 125/300
337/337 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 1480.5753 - mae: 15.4534 - val_loss: 343.1718 - val_mae: 9.3798
Epoch 126/300
337/337 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 1541.6794 - mae: 18.9121 - val_loss: 244.4542 - val_mae: 8.4644
Epoch 127/300
337/337 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 979.6660 - mae: 16.0444 - val_loss: 641.9115 - val_mae: 12.2402
Epoch 128/300
337/337 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 1437.2081 - mae: 18.2404 - val_loss: 341.7108 - val_mae: 9.1649
Epoch 129/300
337/337 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 1017.1462 - mae: 15.5830 - val_loss: 411.2741 - val_mae: 9.8700
Epoch 130/300
337/337 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 1189.5898 - mae: 16.3900 - val_loss: 573.5117 - val_mae: 11.3793
Epoch 131/300
337/337 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 1818.3907 - mae: 16.9342 - val_loss: 301.1472 - val_mae: 9.0333
Epoch 132/300
337/337 ━━━━━━━━━━━━━━━━━━━━ 1s 4ms/step - loss: 1689.0559 - mae: 17.3539 - val_loss: 222.2290 - val_mae: 8.3964
Epoch 133/300
337/337 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 1223.6500 - mae: 14.6763 - val_loss: 549.3686 - val_mae: 11.0395
Epoch 134/300
337/337 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 1765.3545 - mae: 19.6944 - val_loss: 285.8185 - val_mae: 8.6343
Epoch 135/300
337/337 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 1604.8402 - mae: 16.6584 - val_loss: 250.4574 - val_mae: 8.2873
Epoch 136/300
337/337 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 1696.7079 - mae: 19.2996 - val_loss: 258.6632 - val_mae: 8.1826
Epoch 137/300
337/337 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 1775.0745 - mae: 19.1865 - val_loss: 242.9329 - val_mae: 8.2324
Epoch 138/300
337/337 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 890.9003 - mae: 13.4151 - val_loss: 318.7061 - val_mae: 9.0001
Epoch 139/300
337/337 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 1104.3055 - mae: 14.0703 - val_loss: 613.9401 - val_mae: 11.6551
Epoch 140/300
337/337 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 917.3593 - mae: 15.3763 - val_loss: 504.9031 - val_mae: 10.6670
Epoch 141/300
337/337 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 2019.2504 - mae: 21.2095 - val_loss: 212.9487 - val_mae: 7.9226
Epoch 142/300
337/337 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 1159.8757 - mae: 15.7198 - val_loss: 595.9514 - val_mae: 11.5131
Epoch 143/300
337/337 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 1463.1113 - mae: 16.5933 - val_loss: 297.8874 - val_mae: 8.8643
Epoch 144/300
337/337 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 1169.6995 - mae: 16.6608 - val_loss: 543.7133 - val_mae: 11.0458
Epoch 145/300
337/337 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 780.7748 - mae: 12.3564 - val_loss: 463.9521 - val_mae: 10.6758
Epoch 146/300
337/337 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 1069.8610 - mae: 13.7948 - val_loss: 302.6165 - val_mae: 8.6398
Epoch 147/300
337/337 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 1047.7584 - mae: 14.4162 - val_loss: 323.7228 - val_mae: 8.9285
Epoch 148/300
337/337 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 1326.3003 - mae: 16.7238 - val_loss: 910.2513 - val_mae: 13.3783
Epoch 149/300
337/337 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 1345.3563 - mae: 18.3133 - val_loss: 714.4095 - val_mae: 12.5454
Epoch 150/300
337/337 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 1165.8516 - mae: 15.3610 - val_loss: 438.7077 - val_mae: 10.2690
Epoch 151/300
337/337 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 704.4055 - mae: 13.1900 - val_loss: 1141.7804 - val_mae: 15.3611
Epoch 152/300
337/337 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 1905.6018 - mae: 20.2661 - val_loss: 600.6603 - val_mae: 11.7352
Epoch 153/300
337/337 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 1359.2142 - mae: 16.4046 - val_loss: 334.3618 - val_mae: 9.2621
Epoch 154/300
337/337 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 989.2397 - mae: 13.4820 - val_loss: 411.1524 - val_mae: 9.9552
Epoch 155/300
337/337 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 1566.8525 - mae: 17.9032 - val_loss: 336.5973 - val_mae: 9.2863
Epoch 156/300
337/337 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 2905.1497 - mae: 22.3092 - val_loss: 373.5894 - val_mae: 9.5260
Epoch 157/300
337/337 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 1335.3750 - mae: 16.1908 - val_loss: 437.1797 - val_mae: 10.2902

In [123]:
y_pred=model.predict(x_test)

2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 60ms/step

In [129]:
r2=r2_score(y_test,y_pred)

In [138]:
r2

0.9723242420032